[package]
name = "choice"
version = "1.1.0"
authors = [""]
edition = "2018"
description = "Common choice types"
license = "Apache-2.0"
repository = "https://github.com/danvaneijck/choice_exchange"
homepage = "https://choice.exchange"
documentation = ""

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
# for quicker tests, cargo test --lib
# for more explicit tests, cargo test --features=backtraces

[dependencies]
cw2                  = { version = "2.0.0" }
cw20                 = { version = "2.0.0" } 
cosmwasm-schema      = { version = "1.5.0" }
cosmwasm-std         = { version = "2.1.0", features = [ "abort", "cosmwasm_1_2", "cosmwasm_1_3", "cosmwasm_1_4", "cosmwasm_2_0", "iterator", "stargate" ] }

injective-cosmwasm   = { version = "0.3.1" }
injective-math       = { version = "0.3.0" }

schemars = "0.8.10"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }

